

library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(readr)
library(GGally)
library(ISLR)
library(tree)
library(MASS)
library(randomForest)
library(boot)
library(caret)
library(rpart)
library(rpart.plot)
library(gbm)
library(tidymodels)

EmployeeData<-read_csv("HR-Employee-Attrition.csv")